server:
  port: 80

eureka:
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版

ribbon:
  #建立链接所用的时间
  ReadTimeout: 5000
  #建立链接后从服务器读取到可用资源的时间
  ConnectTimeout: 5000
logging:
  level:
    com.liufei.service.Paymentservice: debug
