server:
  port: 8081
eureka:
  client:
    register-with-eureka: true #false表示不向注册中心注册自己
    fetch-registry: true  #false表示自己就是注册中心
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8081
    lease-expiration-duration-in-seconds: 2 # 默认90秒
    lease-renewal-interval-in-seconds: 1 # 默认30秒

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liufei.bean