server:
  port: 80
eureka:
  client:
    register-with-eureka: true #false表示不向注册中心注册自己
    fetch-registry: true  #false表示自己就是注册中心
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: hystrix-feign-order-80


